table orders {
    id int [pk]
    employeeId int [ref: - employees.id]
    delivererId int [ref: - employees.id]
    price float
    tip float
    dateAndTime datetime
}

table employees {
    id int [pk]
    email varchar
    fullName varchar
    deliverer boolean
}

table orderPizzas {
    id int [pk]
    orderId int [ref: > orders.id]
    pizzaId int [ref: > pizzas.id]
}

table pizzas {
    id int [pk]
    sizeId int [ref: - pizzaSizes.id]
    cheeseId int [ref: - cheeses.id]
    sauceId int [ref: - sauces.id]
}

table pizzaToppings {
    id int [pk]
    pizzaId int [ref: > pizzas.id]
    toppingId int [ref: > toppings.id]
}

table pizzaSizes {
    id int 
    type varchar
    size int 
    cost float 
}   

table cheeses {
    id int [pk]
    type varchar
}

table sauces {
    id int [pk]
    flavor varchar
}

table toppings {
    id int [pk]
    type varchar 
    cost float
}
